name: Dev build && upload to s3

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn 
      - run: yarn build-only 
      - name: upload file to tencent cos
        uses: haloislet/cos-action@v2 
        with:
          COMMAND: coscmd upload -r ./docs/ /
          SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          BUCKET: ${{ secrets.COS_BUCKET }}
          REGION: ${{ secrets.COS_REGION }}
#        uses: TencentCloud/cos-action@v1
#        with:
#          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
#          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
#          cos_bucket: ${{ secrets.COS_BUCKET }}
#          cos_region: ${{ secrets.COS_REGION }}
#          local_path: 'docs'
#          remote_path: '' 
#      - name: upload file to s3
#        uses: shallwefootball/upload-s3-action@v1.3.3
#        with:
#          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws_bucket: ${{ vars.DEV_AWS_S3_BUCKET }}
#          source_dir: 'docs'
#          destination_dir: ''
#      - name: Invalidate CloudFront
#        uses: chetan/invalidate-cloudfront-action@v2
#        env:
#          DISTRIBUTION: ${{ vars.DEV_DISTRIBUTION }}
#          PATHS: "/*"
#          AWS_REGION: "us-east-1"
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      - name: send telegram message on deploy
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            Cubicup Demo 前端已部署成功!
#            ${{ github.actor }} created commit:
#            Commit message: ${{ github.event.commits[0].message }}
#
#            Repository: ${{ github.repository }}
#
#            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
