name: Dev build && upload to s3

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn 
      - run: yarn build-only 

      - name: install Tencent commad
        run: |
           sudo pip install coscmd
           sudo pip  install tccli
      - name: confgiure env
#        uses: haloislet/cos-action@v2 
        env:
#          COMMAND: coscmd upload -r ./docs/ /
          SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          BUCKET: ${{ secrets.COS_BUCKET }}
          REGION: ${{ secrets.COS_REGION }}
        run: |
           coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
           tccli configure set secretId $SECRET_ID
           tccli configure set secretKey $SECRET_KEY
           tccli configure set region $REGION
      - name: upload file and invalidate teo
        run: |
            coscmd upload -r ./docs/ /
            tccli teo CreatePurgeTask --cli-unfold-argument   --Targets http://battleship-dev.cubicgames.xyz/  --Type purge_prefix  --ZoneId zone-2l9wjhsgzmhu
